FROM python:slim

LABEL version="3.1.0"
LABEL repository="https://github.com/viewv/sduhealth"
LABEL maintainer="nekokiku <yhfpro@hotmail.com>"

ENV TZ Asia/Shanghai \
    APP_DIR=/app 

RUN apt-get update && \
    apt-get install -y python \
                       python-dev \
                       python-pip && \
    rm -rf /var/lib/apt/lists/*

RUN mkdir -p /app \
    && cd /app \
    && git clone -b main https://github.com/viewv/sduhealth.git \
    && cd sduhealth \
    && pip install --no-cache-dir -r /requirements.txt

WORKDIR ${APP_DIR}

ENTRYPOINT ["/entrypoint.sh"]
